In [1]:
import cv2

In [4]:
im_g = cv2.imread("smallgray.png", 0) # 0 = grayscale, 1 = BGR scale
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [6]:
cv2.imwrite("newsmallgray.png", 0)


True

In [10]:
# indexing
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [11]:
# Printing
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [12]:
# Transform
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [13]:
# Iterrating
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [17]:
import numpy
ims = numpy.hstack((im_g, im_g)) # insert tuple

In [18]:
ims # next to each other

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [19]:
print(ims)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [21]:
# stack vertically
ims = numpy.vstack((im_g, im_g)) # insert tuple
print(ims)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [22]:
# Splitting
lst = numpy.hsplit(ims, 3) # will confuse which column to divide

ValueError: array split does not result in an equal division

In [25]:
lst = numpy.hsplit(ims, 5) # will give 5 columns
print(lst)

[array([[187],
       [198],
       [209],
       [187],
       [198],
       [209]], dtype=uint8), array([[158],
       [125],
       [134],
       [158],
       [125],
       [134]], dtype=uint8), array([[104],
       [255],
       [255],
       [104],
       [255],
       [255]], dtype=uint8), array([[121],
       [255],
       [ 97],
       [121],
       [255],
       [ 97]], dtype=uint8), array([[143],
       [147],
       [182],
       [143],
       [147],
       [182]], dtype=uint8)]


In [26]:
lst = numpy.vsplit(ims, 3) # will give 3 rows
print(lst)

[array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8), array([[209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143]], dtype=uint8), array([[198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)]
